# Generated by Django 3.2.9 on 2021-12-23 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('dozen_price', models.IntegerField(blank=True, default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_rank', models.IntegerField(default=0)),
                ('batch_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('batch_expiry_date', models.DateTimeField(blank=True)),
                ('item_purchased', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
