# Generated by Django 3.2.9 on 2021-12-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
