# Generated by Django 3.2.9 on 2021-12-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_dozen_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dozen_price',
            field=models.IntegerField(blank=True),
        ),
    ]
