# Generated by Django 3.2.9 on 2021-12-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sale_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-updated']},
        ),
    ]
