# Generated by Django 3.2.9 on 2021-12-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_sale_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-time_sold']},
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='updated',
            new_name='time_sold',
        ),
    ]
