# Generated by Django 3.2.9 on 2022-01-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211230_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-quantity', '-price']},
        ),
        migrations.AlterField(
            model_name='item',
            name='dozen_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
