# Generated by Django 3.2.9 on 2022-01-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_sale_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-quantity', '-price']},
        ),
    ]
