# Generated by Django 3.2.9 on 2022-01-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
