# Generated by Django 3.2.9 on 2022-01-26 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
