# Generated by Django 3.2.9 on 2022-01-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_item_time_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
